### ISSUE TITLE
ch03 controllers main.py

### ISSUE THREAD

**Issue by hosamhamdy258** [PacktPublishing/Odoo-15-Development-Essentials#11]
at page 113 there's extra quote as marked in image

![113](https://github.com/PacktPublishing/Odoo-15-Development-Essentials/assets/80757319/7d71848b-b312-4547-b5fc-aa464ed089ed)

**Comment by simranudasi23** [comment]
> at page 113 there's extra quote as marked in image
> 
> ![113](https://user-images.githubusercontent.com/80757319/264381468-7d71848b-b312-4547-b5fc-aa464ed089ed.PNG)

Hey,

Thank you for letting us know about this. Will add it in readme for other user to know about it. Thank you.

Regards,
Packt.
